### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by thegamerx1** [Earthcomputer/clientcommands#108]
```
[Launcher] Processing post-launch actions. Assist launch: false
===============================================================================================
> [00:04:15] [main/INFO]: Loading for game Minecraft 1.14.4
> [00:04:18] [main/INFO]: [FabricLoader] Loading 32 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+933c24c242, fabric-networking-blockentity-v0@0.2.1+28f8190f42, multiconnect-api@1.2.1, fabric-keybindings-v0@0.1.1+933c24c242, fabricloader@0.7.8+build.184, fabric-renderer-indigo@0.1.14+28f8190f42, fabric-containers-v0@0.1.3+28f8190f42, fabric-dimensions-v1@0.1.1+28f8190f42, fabric-biomes-v1@0.1.1+28f8190f42, fabric-crash-report-info-v1@0.1.2+28f8190f42, fabric-events-interaction-v0@0.1.2+28f8190f42, clientcommands@2.3.7-pre5, fabric-api-base@0.1.2+28f8190f42, fabric-rendering-v0@0.1.2+28f8190f42, fabric-rendering-data-attachment-v1@0.1.2+28f8190f42, fabric-resource-loader-v0@0.1.4+28f8190f42, fabric-textures-v0@0.1.4+933c24c242, fabric-content-registries-v0@0.1.2+28f8190f42, fabric-tag-extensions-v0@0.1.3+d423005742, fabric-rendering-fluids-v1@0.1.3+28f8190f42, fabric-commands-v0@0.1.2+28f8190f42, fabric-registry-sync-v0@0.2.3+28f8190f42, fabric-mining-levels-v0@0.1.1+28f8190f42, fabric-loot-tables-v1@0.1.1+28f8190f42, fabric-events-lifecycle-v0@0.1.1+28f8190f42, fabric@0.4.2+build.246-1.14, fabric-particles-v1@0.1.1+933c24c242, fabric-models-v0@0.1.0+933c24c242, fabric-item-groups-v0@0.1.1+28f8190f42, fabric-object-builders-v0@0.1.2+28f8190f42, fabric-networking-v0@0.1.4+28f8190f42
> [00:04:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/TheGamerX05/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
> [00:04:21] [main/WARN]: Error loading class: net/minecraft/class_4717 (java.lang.ClassNotFoundException: net/minecraft/class_4717)
> [00:04:21] [main/WARN]: @Mixin target net.minecraft.class_4717 was not found mixins.clientcommands.json:MixinCommandSuggestor
> Completely ignored arguments: [-noverify]
> org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method modifyWindowTitle(Ljava/lang/String;)Ljava/lang/String; in mixins.clientcommands.json:MixinMinecraftClient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap clientcommands-refmap.json
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
> 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at net.minecraft.client.main.Main.main(Main.java:155)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
> 	... 2 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
> 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at net.minecraft.client.main.Main.main(Main.java:155)
> 	... 7 more
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method modifyWindowTitle(Ljava/lang/String;)Ljava/lang/String; in mixins.clientcommands.json:MixinMinecraftClient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap clientcommands-refmap.json
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
> 	... 14 more
> 2020-02-25 00:04:21,957 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
> org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method modifyWindowTitle(Ljava/lang/String;)Ljava/lang/String; in mixins.clientcommands.json:MixinMinecraftClient failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap clientcommands-refmap.json
> 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
> 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
> 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
> 	at java.lang.ClassLoader.loadClass(Unknown Source)
> 	at net.minecraft.client.main.Main$2.run(Main.java:138)
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (43 ms)
[Launcher] Minecraft closed with exit code: 1
Here I am!
[Launcher] Launcher exited.```

**Comment by Earthcomputer** [comment]
Hello, it looks like you are trying to use the 1.15.2 version of the mod on 1.14.4. Please update to 1.15.2. Thanks!

**Comment by thegamerx1** [comment]
wasnt this mod 1.14.4?

**Comment by Earthcomputer** [comment]
Hi, please remember to look at the version numbers when downloading a mod.
![image](https://user-images.githubusercontent.com/13084089/75200028-96fd1e80-575c-11ea-915b-f45536cd4e13.png)

If you absolutely need to use an older version of Minecraft, there are older versions of the mod available for it:
![image](https://user-images.githubusercontent.com/13084089/75200077-ba27ce00-575c-11ea-8e1b-37c9f9fc22c1.png)

Please note that older versions of the mod are not officially supported, so any bugs in those old versions will not be fixed.
