### ISSUE TITLE
update for 1.16 snapshot plz

### ISSUE THREAD

**Issue by Minepig** [Earthcomputer/clientcommands#109]
I've tried the newest release (2.3.7-pre6) on 20w11a. It crashed on startup with a `MixinTransformerError`.

Then I rolled back to 20w09a, and everything seems to be working just fine, except for `/cenchant` command. When I ran 

```
/cenchant --simulate minecraft:diamond_sword with ...
```

It worked just fine. But when I ran

```
/cenchant minecraft:diamond_sword with ...
```

The game just crashed. The crash report:

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/14/20 5:03 PM
Description: keyPressed event handler

java.lang.IllegalAccessError: tried to access field net.minecraft.class_1297.field_5952 from class net.earthcomputer.clientcommands.features.EnchantmentCracker
	at net.earthcomputer.clientcommands.features.EnchantmentCracker.manipulateEnchantments(EnchantmentCracker.java:351)
	at net.earthcomputer.clientcommands.command.CEnchantCommand.cenchant(CEnchantCommand.java:53)
	at net.earthcomputer.clientcommands.command.CEnchantCommand.lambda$register$1(CEnchantCommand.java:30)
	at net.earthcomputer.clientcommands.command.CEnchantCommand$$Lambda$2582/183989358.run(Unknown Source)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.earthcomputer.clientcommands.command.ClientCommandManager.executeCommand(ClientCommandManager.java:46)
	at net.minecraft.class_746.handler$zbm000$onSendChatMessage(class_746.java:1228)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.sendMessage(class_437.java:326)
	at net.minecraft.class_437.sendMessage(class_437.java:319)
	at net.minecraft.class_408.keyPressed(class_408.java:95)
	at net.minecraft.class_309.method_1454(class_309.java:336)
	at net.minecraft.class_309$$Lambda$3035/1845257375.run(Unknown Source)
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_309.method_1466(class_309.java:334)
	at net.minecraft.class_309.method_22678(class_309.java:424)
	at net.minecraft.class_309$$Lambda$3028/1332206765.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:424)
	at net.minecraft.class_309$$Lambda$1725/1667952430.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)
	at net.minecraft.class_1041.method_15998(class_1041.java:301)
	at net.minecraft.class_310.method_1523(class_310.java:1023)
	at net.minecraft.class_310.method_1514(class_310.java:631)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.earthcomputer.clientcommands.features.EnchantmentCracker.manipulateEnchantments(EnchantmentCracker.java:351)
	at net.earthcomputer.clientcommands.command.CEnchantCommand.cenchant(CEnchantCommand.java:53)
	at net.earthcomputer.clientcommands.command.CEnchantCommand.lambda$register$1(CEnchantCommand.java:30)
	at net.earthcomputer.clientcommands.command.CEnchantCommand$$Lambda$2582/183989358.run(Unknown Source)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.earthcomputer.clientcommands.command.ClientCommandManager.executeCommand(ClientCommandManager.java:46)
	at net.minecraft.class_746.handler$zbm000$onSendChatMessage(class_746.java:1228)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.sendMessage(class_437.java:326)
	at net.minecraft.class_437.sendMessage(class_437.java:319)
	at net.minecraft.class_408.keyPressed(class_408.java:95)
	at net.minecraft.class_309.method_1454(class_309.java:336)
	at net.minecraft.class_309$$Lambda$3035/1845257375.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.wrapScreenError(class_437.java:447)
	at net.minecraft.class_309.method_1466(class_309.java:334)
	at net.minecraft.class_309.method_22678(class_309.java:424)
	at net.minecraft.class_309$$Lambda$3028/1332206765.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:424)
	at net.minecraft.class_309$$Lambda$1725/1667952430.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:98)

-- Affected level --
Details:
	All players: 1 total; [class_746['hutr2002'/2427398, l='MpServer', x=-60.35, y=68.00, z=265.47]]
	Chunk stats: Client Chunk Cache: 729, 485
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 7228504248167938154
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (80,63,92), Chunk: (at 0,3,12 in 5,5; contains blocks 80,0,80 to 95,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 56029278 game time, 59128611 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:459)
	at net.minecraft.class_310.method_1587(class_310.java:1966)
	at net.minecraft.class_310.method_1514(class_310.java:649)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 20w09a
	Minecraft Version ID: 20w09a
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 461368208 bytes (439 MB) / 1466433536 bytes (1398 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx2048m
	Fabric Mods: 
		carpet: Carpet Mod in Fabric 1.3.12
		carpet-extra: Carpet Extra 1.3.13
		clientcommands: Client Commands 2.3.7-pre6
		fabric: Fabric API 0.4.33+build.301-1.16
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d1e
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.0+b7436cca1e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea891e
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d1e
		fabric-containers-v0: Fabric Containers (v0) 0.1.4+9421522d1e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d1e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d1e
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.5+9421522d1e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.8+9421522d1e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d1e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e11e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d61e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff21e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d1e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d61e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+9421522d1e
		fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522d1e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c31e
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d61e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.7+9421522d1e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+2f56dff21e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.25+2f56dff21e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a601e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d1e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed91e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104901e
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104901e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b31e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915801e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba71e
		fabricloader: Fabric Loader 0.7.8+build.184
		itemscroller: Item Scroller 0.15.0-dev.20200229.035553
		litematica: Litematica 0.0.0-dev.20200229.040709
		malilib: MaLiLib 0.10.0-dev.20+beta.2
		minecraft: Minecraft 1.16-alpha.20.9.a
		minihud: MiniHUD 0.19.0-dev.20200229.040421
		modmenu: Mod Menu 1.10.0+build.28
		multiconnect-api: MultiConnect API 1.2.1
		offlineskins: OfflineSkins 1.15.2-v1-fabric
		tweakeroo: Tweakeroo 0.10.0-dev.20200229.041922
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.4459, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/XeKr+原版红石显示1.13-1.16v1.zip (incompatible)
	Current Language: 简体中文 (中国)
	CPU: 4x Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz
```

**Comment by Minepig** [comment]
At least update it once a while, plz. If you don't want to keep up all the time, just update it when someone reports that the previous one has completely failed (e.g. crash on startup).

**Comment by Earthcomputer** [comment]
No. I start the update process once the pre-release versions start coming out. I don't have the time to update my mods for snapshots.
