### ISSUE TITLE
Opening your inventory while using /cfinditem will crash your game.

### ISSUE THREAD

**Issue by OneYellowLemon** [Earthcomputer/clientcommands#145]
Opening your inventory while using /cfinditem will crash your game. Should be a pretty simple fix, you just need to get the player's inventory keybind and cancel events.

Crash log:
```
[18:11:16] [main/INFO]: [CHAT] Searching for air
[18:11:17] [main/FATAL]: Unreported exception thrown!
java.lang.UnsupportedOperationException: Unable to construct this menu by type
	at net.minecraft.class_1703.method_17358(class_1703.java:66) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at net.earthcomputer.clientcommands.command.FindItemCommand$FindItemsTask$1.accept(FindItemCommand.java:204) ~[clientcommands-2.4.7.jar:?]
	at net.earthcomputer.clientcommands.GuiBlocker.onOpenGui(GuiBlocker.java:17) ~[clientcommands-2.4.7.jar:?]
	at net.minecraft.class_310.handler$zlb000$onOpenScreen(class_310.java:5338) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:1612) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1509) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:996) ~[intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.9.3+build.207-1.16.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.3+build.207.jar:?]
[18:11:17] [main/INFO]: Reloading ResourceManager: Default, Default, Happy Warm Strider.zip, VanillaTweaks_r444960.zip, 6improved-netherite.zip, VisibleDebris.zip, NoNausea.zip, Wrench.zip, AntiGhost, Auto Config v1 Updated, BoundingBoxOutlineReloaded, Clear View, Client Commands, Cloth Config v4, Fabric API, Fabric API Base, Fabric BlockRenderLayer Registration (v1), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking Block Entity (v0), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen Handler API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Loader, Fabric Zero, Light Overlay, Litematica, Lithium, Logical Zoom, MaLiLib, MiniHUD, Mod Menu, MultiConnect API, Orderly, Phosphor, Shulker Box Tootip, Sodium, Tweakeroo
[18:11:17] [main/INFO]: Stopping worker threads
```

**Comment by OneYellowLemon** [comment]
Actually, I was thinking about it, and it would probably be more user-friendly to stop finding items and just return the current total then and there and let them open their inventory instead of cancelling the inventory open event.

**Comment by James103** [comment]
Can reproduce in 1.16.3 with Client Commands 2.4.7 (same stack trace as yours just with extra lines).

**Comment by Earthcomputer** [comment]
Fixed in the next version, which will be released when it's released
