### ISSUE TITLE
Keeps crashing when this mod is enabled.

### ISSUE THREAD

**Issue by Penzillius** [Earthcomputer/clientcommands#24]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 28/04/19 9:41 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:35)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoClassDefFoundError: io/github/cottonmc/clientcommands/ClientCommands
		at de.guntram.mcmod.grid.Grid.registerLocalCommands(Grid.java:339)
		at de.guntram.mcmod.grid.Grid.onInitializeClient(Grid.java:59)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more
	Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.clientcommands.ClientCommands
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:160)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 24 more

**Comment by Earthcomputer** [comment]
You have downloaded the wrong ClientCommands. You wanted https://github.com/CottonMC/ClientCommands

**Comment by Juuxel** [comment]
> Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.clientcommands.ClientCommands

Author of Cotton Client Commands here: You don't have Client Commands installed.

**Comment by Penzillius** [comment]
Wait a fucking second.... Lmao tyvm

**Comment by Penzillius** [comment]
Sorry, but am I supposed to have both Juuxel's and Your clientcommands? If I only have Juuxel's it doesnt have the commands and if I have both it shows this:
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:146)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:107)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'clientcommands': 2.0.0, 0.2.0
	at net.fabricmc.loader.discovery.ModCandidateSet.toSortedSet(ModCandidateSet.java:84)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:112)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:477)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:144)
	... 10 more

**Comment by Juuxel** [comment]
That will be fixed in my version 0.3.0, which changes the mod id to `cotton-client-commands`.

**Comment by Penzillius** [comment]
Oh, so I can't use this just yet?

**Comment by Penzillius** [comment]
Nevermind! I changed the mod ID and it worked fine.
