### ISSUE TITLE
`/citemgroup` remove test crashes client.

### ISSUE THREAD

**Issue by L0um15** [Earthcomputer/clientcommands#272]
Minecraft crashed 3 times in a row while trying to execute `/citemgroup` remove test.

Description: `keyPressed event handler`
Reason?: `net.earthcomputer.clientcommands.mixin.CreativeInventoryScreenAccessor. Mixin is defined in mixins.clientcommands.json and cannot be referenced directly`

[crash-2021-06-04_00.08.46-client.txt](https://github.com/Earthcomputer/clientcommands/files/6594611/crash-2021-06-04_00.08.46-client.txt)

**Comment by xpple** [comment]
Damn, let me have a look.

**Comment by L0um15** [comment]
Wow, that was quick

**Comment by xpple** [comment]
:). Could you by any chance paste the log instead of posting a file?

**Comment by L0um15** [comment]
Ah, i understand

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/4/21 12:08 AM
Description: keyPressed event handler

org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for net.earthcomputer.clientcommands.mixin.CreativeInventoryScreenAccessor. Mixin is defined in mixins.clientcommands.json and cannot be referenced directly
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.removeGroup(ItemGroupCommand.java:131)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.lambda$register$14(ItemGroupCommand.java:101)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.earthcomputer.clientcommands.command.ClientCommandManager.executeCommand(ClientCommandManager.java:73)
	at net.minecraft.class_746.handler$zca000$onSendChatMessage(class_746.java:1261)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.method_25425(class_437.java:313)
	at net.minecraft.class_437.method_25427(class_437.java:306)
	at net.minecraft.class_408.method_25404(class_408.java:98)
	at net.minecraft.class_309.method_1454(class_309.java:345)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_309.method_1466(class_309.java:343)
	at net.minecraft.class_309.method_22678(class_309.java:433)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:433)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.removeGroup(ItemGroupCommand.java:131)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.lambda$register$14(ItemGroupCommand.java:101)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.earthcomputer.clientcommands.command.ClientCommandManager.executeCommand(ClientCommandManager.java:73)
	at net.minecraft.class_746.handler$zca000$onSendChatMessage(class_746.java:1261)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.method_25425(class_437.java:313)
	at net.minecraft.class_437.method_25427(class_437.java:306)
	at net.minecraft.class_408.method_25404(class_408.java:98)
	at net.minecraft.class_309.method_1454(class_309.java:345)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_309.method_1466(class_309.java:343)
	at net.minecraft.class_309.method_22678(class_309.java:433)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:433)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
	All players: 1 total; [class_746['L0um15'/186, l='ClientLevel', x=43.43, y=70.00, z=170.66]]
	Chunk stats: Client Chunk Cache: 841, 570
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,64,128), Chunk: (at 0,4,0 in 4,8; contains blocks 64,0,128 to 79,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3589 game time, 3589 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by xpple** [comment]
Did the group `test` exist?

**Comment by L0um15** [comment]
yes

**Comment by xpple** [comment]
Alright. Could you give me the steps to reproduce this crash?

**Comment by L0um15** [comment]
Clean instance of MultiMC
| Mods | ---          |
| ------------- |:-------------:|
| Client commands      | Latest |
| Fabric API      | 0.34.6+16 | 

I have created a item group called `test` with `acacia_planks` as icon
then i tried to create same itemgroup second time, (i was checking translation)
Obviously error occured saying that i cannot.
Then i tried to remove item group which caused minecraft to crash.

Everytime i try to use `remove` arg. Crash occurs.

Also i am using AdoptJDK 8 with Hotspot

**Comment by L0um15** [comment]
If itemgroups are saved in text format as json or yaml i could tell you if test is still there, Tab-completion shows that test still exists.

**Comment by xpple** [comment]
The item groups are saved in `.minecraft/config/clientcommands/groups.dat`.

**Comment by L0um15** [comment]
Yes, it is there. I tried to add some items to the itemgroup, still crashes

**Comment by xpple** [comment]
That makes sense, the file is saved after where your client crashed. What I'm thinking is that your crash is related to some Mixin stuff - which I know very little about. I hope someone else might know what's going on.

**Comment by barraIhsan** [comment]
Yes, it also crashes because of keyPressed event handler. I think its impossible to do, as said in [here](https://github.com/Earthcomputer/clientcommands/issues/235#issuecomment-821494195). Maybe just relog to apply changes?

**Comment by L0um15** [comment]
> Maybe just relog to apply changes?

There is nothing to apply, since you cant even try to remove itemgroup . Crash occurs before changes are saved.

The only way is to edit file manually.

**Comment by xpple** [comment]
> Yes, it also crashes because of keyPressed event handler. I think its impossible to do, as said in [here](https://github.com/Earthcomputer/clientcommands/issues/235#issuecomment-821494195). Maybe just relog to apply changes?

Well it’s not impossible - it’s working completely fine for me. I tried to reproduce this bug but couldn’t.

**Comment by L0um15** [comment]
I could upload a footage of occuring problem to youtube with all steps to reproduce

**Comment by L0um15** [comment]
Actually, im going to do that.

**Comment by xpple** [comment]
Sure!

**Comment by L0um15** [comment]
Here you go, full footage without any edits.

Completly recompiled clientcommands with fresh instance of 1.16.5

https://www.youtube.com/watch?v=hPpQZbX2zqg

**Comment by xpple** [comment]
First of all, shoutout to you for having installed my mod - I appreciate it!

Secondly, I think the problem could be caused by one of two things:
- MultiMC
- Java 16
I doubt it's MultiMC, though. And since cc just updated, I'll be trying out Java 16, and I'll see if that changes things.

**Comment by xpple** [comment]
It turns out Java 16 wasn't the issue, it would have been quite silly if it had been, lol. I don't use MultiMC personally, so someone who does, please try it out for me.

**Comment by L0um15** [comment]
I tested java 16 + java8 on footage. Now im testing official launcher

**Comment by L0um15** [comment]
Turns out official launcher with bundled java 8 also crashes, so this is not MultiMC related.

**Comment by xpple** [comment]
I am beyond confused.

**Comment by L0um15** [comment]
New parts for custom pc are being delivered in July. Maybe this will help. 😂

**Comment by xpple** [comment]
Wait! Actually, I think I know what’s going on! I’ve been running clientcommands in the development environment all this time... and guess what Mixin is using a mapped classpath, lol.

**Comment by L0um15** [comment]
Debugging is fun, and painful

**Comment by L0um15** [comment]
Push changes to your fork, so i could check it once im back home.
