### ISSUE TITLE
/cglow block crashes you're game (1.17)

### ISSUE THREAD

**Issue by nirmall8771** [Earthcomputer/clientcommands#279]
When i do /cglow block [coords] my game crashes, this is only in 1.17

**Comment by Earthcomputer** [comment]
Can you give the crash log please?

**Comment by nirmall8771** [comment]
[crash-2021-06-10_18.34.09-client.txt](https://github.com/Earthcomputer/clientcommands/files/6633064/crash-2021-06-10_18.34.09-client.txt)
```---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/06/2021, 18:34
Description: Unexpected error

java.lang.IllegalStateException: Not filled all elements of the vertex
	at net.minecraft.class_287.method_1344(class_287.java:283)
	at net.earthcomputer.clientcommands.render.Line.putVertex(Line.java:52)
	at net.earthcomputer.clientcommands.render.Line.renderLine(Line.java:37)
	at net.earthcomputer.clientcommands.render.Cuboid.render(Cuboid.java:42)
	at net.earthcomputer.clientcommands.render.RenderQueue.lambda$render$3(RenderQueue.java:69)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at net.earthcomputer.clientcommands.render.RenderQueue.render(RenderQueue.java:69)
	at net.minecraft.class_757.handler$zdi000$renderWorldHand(class_757.java:1495)
	at net.minecraft.class_757.method_3188(class_757.java:1024)
	at net.minecraft.class_757.method_3192(class_757.java:806)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_1344(class_287.java:283)
	at net.earthcomputer.clientcommands.render.Line.putVertex(Line.java:52)
	at net.earthcomputer.clientcommands.render.Line.renderLine(Line.java:37)
	at net.earthcomputer.clientcommands.render.Cuboid.render(Cuboid.java:42)
	at net.earthcomputer.clientcommands.render.RenderQueue.lambda$render$3(RenderQueue.java:69)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at net.earthcomputer.clientcommands.render.RenderQueue.render(RenderQueue.java:69)
	at net.minecraft.class_757.handler$zdi000$renderWorldHand(class_757.java:1495)
	at net.minecraft.class_757.method_3188(class_757.java:1024)

-- Affected level --
Details:
	All players: 1 total; [class_746['nirmall'/186, l='ClientLevel', x=162.14, y=52.00, z=-150.92]]
	Chunk stats: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,67,-128), Section: (at 0,3,0 in 12,4,-8; chunk contains blocks 192,0,-128 to 207,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 9411 game time, 9411 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Mac OS X (x86_64) version 10.12.6
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 925521520 bytes (882 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3,30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon R9 M395
	Graphics card #0 vendor: ATI (0x1002)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x6920
	Graphics card #0 versionInfo: Revision ID: 0x0001, ROM Revision: 113-C905AA-799, EFI Driver Version: 01.00.799
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,87
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 0,00
	Memory slot #1 clockSpeed (GHz): -0,00
	Memory slot #1 type: Empty
	Memory slot #2 capacity (MB): 4096,00
	Memory slot #2 clockSpeed (GHz): 1,87
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 0,00
	Memory slot #3 clockSpeed (GHz): -0,00
	Memory slot #3 type: Empty
	Virtual memory max (MB): 10240,00
	Virtual memory used (MB): 6783,11
	Swap memory total (MB): 2048,00
	Swap memory used (MB): 869,75
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		clientcommands: Client Commands 2.5
		clientcommands-scripting: Clientcommands Scripting 1.1
		fabric: Fabric API 0.34.9+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463d5
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+a02b4463d5
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e13d5
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b4463d5
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b4463d5
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afad5
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b4463d5
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b4463d5
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da310d5
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b4463d5
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b4463d5
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b4463d5
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afad5
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b4463d5
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab6121d5
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463d5
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3ed5
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b4463d5
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afad5
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b4463d5
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121d5
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b4463d5
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b4463d5
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b4463d5
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.9+a02b4463d5
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+a02b4463d5
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b4463d5
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b4463d5
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afad5
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b4463d5
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.3+b7ab6121d5
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b4463d5
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.10+be9da310d5
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b4463d5
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabricloader: Fabric Loader 0.11.3
		java: OpenJDK 64-Bit Server VM 16
		malilib: MaLiLib 0.10.0+dev.22
		minecraft: Minecraft 1.17
		minihud: MiniHUD 0.19.0-dev.20210608.211830
		multiconnect-api: MultiConnect API 1.4
		tweakeroo: Tweakeroo 0.10.0-dev.20210608.211857
		voicechat: Simple Voice Chat 1.17-1.0.1
	Launched Version: fabric-loader-0.11.3-1.17
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon R9 M395 OpenGL Engine GL version 4.1 ATI-1.54.3, ATI Technologies Inc.
	Window size: 5120x2880
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (United Kingdom)
	CPU: 4x Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
	Player Count: 1 / 8; [class_3222['nirmall'/186, l='ServerLevel[New World]', x=162.14, y=52.00, z=-150.92]]
	Data Packs: vanilla (incompatible), Fabric Mods```
Here you go.

**Comment by Earthcomputer** [comment]
It's already fixed.
