### ISSUE TITLE
tried multiple versions of fabric and they all crash when i add this mod in

### ISSUE THREAD

**Issue by epilimic** [Earthcomputer/clientcommands#28]
Fabric by itself loads fine but when I drop this in the mods folder I get this crash. Have tried about 7 different fabric versions and the same thing happens on each.

```
[03:22:28] [ForkJoinPool-1-worker-3/WARN]: Mod ID clientcommands uses outdated schema version: 0 < 1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:143)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Unsatisfied dependencies!
 - Mod clientcommands depends on mod fabric @ *, which is missing!
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:296)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:448)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:141)
	... 10 more
Exiting with -1
Process exited with code -1.
```

**Comment by epilimic** [comment]
Nevermind. The instructions for this failed to mention you also needed the API.

**Comment by leumasme** [comment]
Close?

**Comment by Earthcomputer** [comment]
Instructions say you need the API.
