### ISSUE TITLE
Incompatible with HDSkins (Kirin UI)

### ISSUE THREAD

**Issue by enchanted-sword** [Earthcomputer/clientcommands#285]
Attempting to load Minecraft with both mods active sends me straight to the Not Enough Crashes menu, which displays the following crash report.

[crash-2021-06-22_12.54.48-client.txt](https://github.com/Earthcomputer/clientcommands/files/6696070/crash-2021-06-22_12.54.48-client.txt)

```
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 22/06/21 12:54 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at net.earthcomputer.clientcommands.command.FakeCommandSource.<init>(FakeCommandSource.java:13)
	at net.earthcomputer.clientcommands.features.RenderSettings.preRenderEntities(RenderSettings.java:37)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.handler$bkl000$onConfigure(EntityRenderDispatcher:3067)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.configure(EntityRenderDispatcher)
	at com.minelittlepony.common.client.gui.OutsideWorldRenderer.configure(OutsideWorldRenderer.java:42)
	at com.minelittlepony.common.client.gui.OutsideWorldRenderer.renderStack(OutsideWorldRenderer.java:57)
	at com.minelittlepony.common.client.gui.sprite.ItemStackSprite.render(ItemStackSprite.java:33)
	at com.minelittlepony.common.client.gui.element.Button.renderButton(Button.java:144)
	at net.minecraft.client.gui.widget.AbstractButtonWidget.render(AbstractButtonWidget:86)
	at net.minecraft.client.gui.screen.Screen.render(Screen:81)
	at net.minecraft.client.gui.screen.TitleScreen.render(TitleScreen:287)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
Details:
	Screen name: net.minecraft.class_442
	Mouse location: Scaled: (189, 80). Absolute: (759.000000, 322.000000)
	Screen size: Scaled: (480, 300). Absolute: (1920, 1200). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:619)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 968703192 bytes (923 MB) / 3152543744 bytes (3006 MB) up to 6681526272 bytes (6372 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7168m -Xms7168m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Suspected Mods: Kirin UI (kirin), Client Commands (clientcommands), Fabric Loader (fabricloader)
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.9
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.12
		advancementinfo: AdvancementInfo 1.16.5-fabric0.30.0-1.2
		afkpeace: AFKPeace 4.6.0
		afktape: AFKTape 1.1.1
		amecs: Amecs 1.3.4+mc.1.16.3
		amecsapi: Amecs API 1.1.4+mc1.16.5
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.17.22
		armor-visibility: Armor Visibility 1.0.1
		armorhotswap: ArmorHotswap 1.2
		artifice: Artifice 0.14.6+1.16.5
		auto_third_person: Auto Third Person 1.1.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		baritone: Baritone 1.6.3
		bclib: BCLib 0.1.42
		beem: Beem 1.3.3
		beenfo: Beenfo 1.16.5-fabric0.30.0-1.3.1
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.9.8.2-pre
		bettermounthud: Better Mount HUD 1.0.1
		betternether: Better Nether 5.0.7
		betterpingdisplay: Better Ping Display 1.1
		blockus: Blockus 2.1.4+1.16.5
		blue_endless_jankson: jankson 1.2.0
		bookdupe: BookDupe 1.0.2
		boostedbrightness: Boosted Brightness 2.0.0
		borderlessmining: Borderless Mining 1.0.6+1.16.2
		breakprogress: Break Progress 1.0.1
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
		capes: Capes 1.1.2
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		cct: Command Creative Tab Mod 1.2.1
		chesttracker: Chest Tracker 0.8.13
		clear-skies: Clear Skies 1.5.55
		clearview: Clear View 2.1
		clientcommands: Client Commands 2.4.10
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config-lite: cloth-config-lite 1.0.4
		cloth-config2: Cloth Config v4 4.11.26
		cloth-utils-v1: Cloth Utils v1 1.4.5
		cmdkeybind: Command Macros 1.5.2-1.16
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		commonformatting: common formatting 1.0.1
		computercraft: CC:T for Fabric 1.91.2
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		coworigin: Tauren idc
		craftpresence: CraftPresence 1.8.2
		crowdin-translate: CrowdinTranslate 1.3+1.16
		cullleaves: Cull Leaves 2.1.0
		cullparticles: Cull Particles 2.0
		daemonic: Daemonic 1.0.0
		de_javagl_obj: obj 0.3.0
		dontdropit: Don't Drop It! 2.2.1+1.16
		durabilityviewer: Giselbaers Durability Viewer 1.16.5-fabric0.30.0-1.10
		dynamicfps: Dynamic FPS 2.0.2
		ears: Ears 1.2.2
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		eggtab: Egg Tab 2.1.0+1.16-fabric
		enchant_giver: Enchant Giver 1.0.3
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.1
		enhancedblockentities: Enhanced Block Entities 0.3.1
		entityculling: EntityCulling-Fabric 1.2.2
		entityoutliner: Entity Outliner 1.0.0
		enva: Environmental Armor 1.3.1
		extraorigins: Extra Origins 1.16.5-11
		fabric: Fabric API 0.36.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.1+kotlin.1.5.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+0ef801b67d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fabrishot: Fabrishot 1.4.0
		fallflyinglib: FallFlyingLib 1.1.0
		fiber: fiber 0.23.0-2
		figura: Figura 0.0.5
		flighthud: Flight HUD 1.16.3-fabric-6
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		hdskins: HD Skins 6.3.6-1.16.5
		here-be-no-dragons: Here be no Dragons! 1.0.0
		horseinfo: Horse Info 0.2.2-1.16.1
		hydrogen: Hydrogen 0.2
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.5.1
		impersonate: Impersonate 2.1.0
		indium: Indium 1.0.0
		inventoryhud: Inventory HUD + 3.1.3
		inventorytabs: Inventory Tabs 0.3.0-1.16.4
		itemmodelfix: Item Model Fix 1.0.2+1.16
		itemscroller: Item Scroller 0.15.0-dev.20210111.205029
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		javax_vecmath_vecmath: vecmath 1.5.2
		kirin: Kirin UI 1.7.1-1.16.5
		kyrptconfig: Kytpt Config 1.1.5-1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		letsencryptcraft: Let's Encrypt Craft 1.4.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.3.5+1.16.5
		lionutils: LionUtils 7.0.0+1.16
		litematica: Litematica 0.0.0-dev.20210120.213004
		lithium: Lithium 0.6.6
		lootbeams: Lootbeams 2.0.2
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		mcct: MC Client Tweaks 1.4.0-1.16
		mcda: MC Dungeons Armors 1.4.1
		mcdw: MC Dungeons Weapons 3.1.0
		megane: megane 4.1.3
		megane-base: megane-base 4.1.3
		megane-runtime: megane-runtime 4.1.3
		megane-vanilla: megane-vanilla 4.1.3+1.16.5
		microconfig: Microconfig 2.0.1
		minecraft: Minecraft 1.16.5
		minelp: Mine Little Pony 4.2.4-1.16.5
		minihud: MiniHUD 0.19.0-dev.20201103.184029
		mm: Manningham Mills 2.1
		moborigins: Mob Origins 1.4.0
		mod-info-cmd: Mod Info Command 0.0.1
		modmenu: Mod Menu 1.16.9
		modupdater: ModUpdater 1.1.9+1.16.2
		more_tooltips: MoreTooltips 1.0.1
		mson: Mson 1.2.2-1.16.5-1.16
		multiconnect-api: MultiConnect API 1.3.9
		mycommands: MyCommands Fabric 1.16.1-17
		namepain: Name Pain 1.3.1
		nbttooltip: NBT Tooltip 1.2.0-fabric
		nomoreglowingpots: No More Glowing Pots 1.0.2
		notenoughanimations: NotEnoughAnimations 1.2.4
		notenoughcrashes: Not Enough Crashes 3.2.0
		numerusromani: Numerus Romani 0.0.4
		orderly: Orderly 2.0.0-alpha.10-1.16
		org_apache_httpcomponents_httpmime: httpmime 4.3.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_luaj_luaj-jse: luaj-jse 3.0.1
		origins: Origins 0.7.0
		origins-classes: Origins: Classes 1.1.1
		originsplus: Origins Plus 0.0.2
		originsumbrellas: Origins: Umbrellas 1.1.0
		overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
		patchouli: Patchouli 1.16.4-51-FABRIC
		pehkui: Pehkui 2.0.0+21w14a
		petowner: Pet Owner 1.8.0-1.16.5+
		phonos: Phonos 0.1.1-beta
		phormat: phormat 1.0.0
		phosphor: Phosphor 0.7.2+build.12
		pling: Pling 1.3.0
		portal-helper: Portal Helper 1.1.0
		potiondescriptions: Potion Descriptions fabric-1.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		rebind_all_the_keys: RebindAllTheKeys 1.1.1
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		roughlyenoughresources: Roughly Enough Resources 2.1.5
		rpg-hud: RPG-Hud 3.8.1
		satin: Satin 1.5.1
		seamless_loading_screen: Seamless Loading Screen 1.3.4
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		signsearcher: Sign Searcher 0.2.1+mc1.16.3
		sit: Sit 1.16.2-9
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		slimeorigin: Slimeorigin 2.1.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sneakyscreens: Sneaky Screens 1.0.1
		sodium: Sodium 0.1.1-SNAPSHOT
		spaceorigin: Astronomian idc
		spruceui: SpruceUI 2.1.4+1.16
		timeorigin: Timeshifter 1.1.1
		toomanyorigins: TooManyOrigins 0.1.0
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-4
		transliterationlib: TRansliterationLib 1.0.4
		tweak-my-client: TweakMyClient 1.1.1+build.14
		tweakeroo: Tweakeroo 0.10.0-dev.20210303.123654
		visualoverhaul: VisualOverhaul 3.2.0
		waila: Hwyla 1.9.22
		whereisit: Where Is It 1.11.7
		wi_zoom: WI Zoom 1.3-MC1.16.5
		wiicustomorigins: WiiDude's Custom Origins Mod 1.16.5-13
		wildfire_gender: Wildfire's Female Gender Mod 2.5.4
		woolorigin: Woolian Origin 1.0.1
		worldedit: WorldEdit 7.2.2+fc3c499
		worldeditcui: WorldEditCUI 1.16.5+02
		xaerominimap: Xaero's Minimap 21.10.0.4
		xaeroworldmap: Xaero's World Map 1.14.1
	Patchouli open book context: n/a
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.51, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, null, Fabric Mods, visualoverhaul/nobottles, visualoverhaul/coloredwaterbucket, slightguimodifications:cts_textures, visualoverhaul/fancyfurnace, cullleaves/smartleaves, file/VanillaTweaks 21-5-30, file/slight-depth-1.16-b5
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0

```

I opened a similar issue report in the Kirin UI github and the owner responded and said the error was an issue with this mod and not Kirin.

![image](https://user-images.githubusercontent.com/81981111/122967763-2fabaa80-d361-11eb-837f-1df16b4ac418.png)

**Comment by Earthcomputer** [comment]
Please test on 1.17 to see if this is still an issue. 1.16.5 is unsupported.
