### ISSUE TITLE
Crash on loading item group that has more than 1 items in single stack

### ISSUE THREAD

**Issue by xlzv** [Earthcomputer/clientcommands#497]
Using latest version of fabric api, client commands

Crash report:
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-01-20 12:57:52
Description: Unexpected error

java.lang.IllegalArgumentException: Stack size must be exactly 1
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.5)
	at net.minecraft.item.ItemGroup$EntriesImpl.add(ItemGroup:226)
	at net.minecraft.item.ItemGroup$Entries.add(ItemGroup:262)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.lambda$loadFile$20(ItemGroupCommand.java:304)
	at net.minecraft.item.ItemGroup.updateEntries(ItemGroup:95)
	at net.minecraft.item.ItemGroups.method_47338(ItemGroups:1918)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.item.ItemGroups.updateEntries(ItemGroups:1918)
	at net.minecraft.item.ItemGroups.updateDisplayParameters(ItemGroups:1934)
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.<init>(CreativeInventoryScreen:182)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.init(InventoryScreen:54)
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen:392)
	at net.minecraft.client.gui.screen.Screen.init(Screen:383)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1049)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1993)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1863)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:781)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1761$class_7703.method_45417(class_1761.java:226)
	at net.minecraft.class_1761$class_7704.method_45420(class_1761.java:262)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.lambda$loadFile$20(ItemGroupCommand.java:304)
	at net.minecraft.class_1761.method_47306(class_1761.java:95)
	at net.minecraft.class_7706.method_47338(class_7706.java:1918)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_7706.method_47337(class_7706.java:1918)
	at net.minecraft.class_7706.method_47330(class_7706.java:1934)
	at net.minecraft.class_481.<init>(class_481.java:182)
	at net.minecraft.class_490.method_25426(class_490.java:54)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_310.method_1508(class_310.java:1993)

-- Affected level --
Details:
	All players: 1 total; [class_746['Whiteman__'/130, l='ClientLevel', x=77.15, y=-49.20, z=72.91]]
	Chunk stats: 961, 615
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 29906 game time, 29906 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1342809608 bytes (1280 MiB) / 3867148288 bytes (3688 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM)2 Quad CPU           @ 2.40GHz
	Identifier: Intel64 Family 6 Model 15 Stepping 7
	Microarchitecture: Core 2 (Client)
	Frequency (GHz): 2.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 650 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x11c6
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 0.80
	Memory slot #0 type: DDR2
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 0.80
	Memory slot #1 type: DDR2
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 0.80
	Memory slot #2 type: DDR2
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 0.80
	Memory slot #3 type: DDR2
	Virtual memory max (MB): 16894.05
	Virtual memory used (MB): 11310.21
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 776.07
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		clientcommands: Client Commands 2.7.8
			clientarguments: clientarguments 1.4.2
		fabric-api: Fabric API 0.72.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.11+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.4+1134c5b885
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.42+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.8+1134c5b885
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.30+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.28+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.3.0+85f102ee85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.0+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabricloader: Fabric Loader 0.14.13
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.19.3
		notenoughcrashes: Not Enough Crashes 4.2.0+1.19.3
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce GTX 650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 456.71, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU @ 2.40GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Whiteman__'/130, l='ServerLevel[New World]', x=77.15, y=-49.20, z=72.91]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Client Commands (clientcommands)
```

**Comment by xpple** [comment]
Could you send your `groups.dat` file that caused the crash?

**Comment by xlzv** [comment]
> Could you send your `groups.dat` file that caused the crash?

any `groups.dat` file contains more than 1 item in single slot causes crash

**Comment by xlzv** [comment]
The issue still remains
```
java.lang.IllegalArgumentException: Stack size must be exactly 1
	at net.minecraft.class_1761$class_7703.method_45417(class_1761.java:234)
	at net.minecraft.class_1761$class_7704.method_45420(class_1761.java:270)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.lambda$loadFile$24(ItemGroupCommand.java:329)
	at net.minecraft.class_1761.method_47306(class_1761.java:96)
	at net.minecraft.class_7706.method_47338(class_7706.java:2009)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.class_7706.method_47337(class_7706.java:2009)
	at net.minecraft.class_7706.method_47330(class_7706.java:2020)
	at net.minecraft.class_481.<init>(class_481.java:182)
	at net.minecraft.class_490.method_25426(class_490.java:56)
	at net.minecraft.class_437.method_25423(class_437.java:427)
	at net.minecraft.class_310.method_1507(class_310.java:1079)
	at net.minecraft.class_310.method_1508(class_310.java:2010)
	at net.minecraft.class_310.method_1574(class_310.java:1880)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by Earthcomputer** [comment]
What how

**Comment by Earthcomputer** [comment]
@xlzv could you post the whole log?

**Comment by Earthcomputer** [comment]
I still don't see how your crash log was possible given the line numbers, but I noticed that `/citemgroup reload` was still broken.
