### ISSUE TITLE
Crash when joning any world

### ISSUE THREAD

**Issue by Omena0** [Earthcomputer/clientcommands#526]
Crash report:
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-05-14 12:57:16
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.earthcomputer.clientcommands.ClientCommands.registerCommands(ClientCommands.java:78)
	at net.fabricmc.fabric.api.client.command.v2.ClientCommandRegistrationCallback.lambda$static$0(ClientCommandRegistrationCallback.java:36)
	at net.minecraft.class_634.handler$zco000$fabric-command-api-v2$onGameJoin(class_634.java:4240)
	at net.minecraft.class_634.method_11120(class_634.java:463)
	at net.minecraft.class_2678.method_11567(class_2678.java:92)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: clientcommands:Custom
	at net.minecraft.class_2960.method_45137(class_2960.java:252)
	at net.minecraft.class_2960.<init>(class_2960.java:47)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.lambda$loadFile$25(ItemGroupCommand.java:323)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.loadFile(ItemGroupCommand.java:311)
	at net.earthcomputer.clientcommands.command.ItemGroupCommand.<clinit>(ItemGroupCommand.java:62)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.earthcomputer.clientcommands.ClientCommands.registerCommands(ClientCommands.java:78)
	at net.fabricmc.fabric.api.client.command.v2.ClientCommandRegistrationCallback.lambda$static$0(ClientCommandRegistrationCallback.java:36)
	at net.minecraft.class_634.handler$zco000$fabric-command-api-v2$onGameJoin(class_634.java:4240)
	at net.minecraft.class_634.method_11120(class_634.java:463)
	at net.minecraft.class_2678.method_11567(class_2678.java:92)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['Omena0MC'/6157, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 841, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 399937592 bytes (381 MiB) / 805306368 bytes (768 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 530
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x191b
	Graphics card #0 versionInfo: DriverVersion=21.20.16.4550
	Graphics card #1 name: NVIDIA GeForce GTX 950M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x139a
	Graphics card #1 versionInfo: DriverVersion=26.21.14.4587
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 32666.52
	Virtual memory used (MB): 10108.70
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 270.56
	JVM Flags: 8 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		clientcommands: Client Commands 2.7.11
			clientarguments: clientarguments 1.4.3
		fabric-api: Fabric API 0.76.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.25+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.4+ae0966baf4
			fabric-commands-v0: Fabric Commands (v0) 0.2.42+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.52+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.7+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.5+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.3+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.25+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.29+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.37+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.22+ca5f59aaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.39+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.1+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.6+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.2+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.0+938a1d56f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.18+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.0.1+9003cbe9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.4
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce GTX 950M/PCIe/SSE2 GL version 3.2.0 NVIDIA 445.87, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
```

No other mods than fabric api and client commands

**Comment by Earthcomputer** [comment]
https://github.com/Earthcomputer/clientcommands/commit/9e514d785d673332d13e8ef8f1244f5d15a5b172
