### ISSUE TITLE
Crash when joining server or loading my own world

### ISSUE THREAD

**Issue by FatSake** [Earthcomputer/clientcommands#544]
logs are here:
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-06-29 05:52:59
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.minecraft.class_634.handler$bpe002$seedcrackerx$onGameJoin(class_634.java:9251)
	at net.minecraft.class_634.method_11120(class_634.java:465)
	at net.minecraft.class_2678.method_11567(class_2678.java:95)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:213)
	at java.base/java.util.List.of(List.java:979)
	at kaptainwutax.seedcrackerX.config.StructureSave.<clinit>(StructureSave.java:29)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_634.handler$bpe002$seedcrackerx$onGameJoin(class_634.java:9251)
	at net.minecraft.class_634.method_11120(class_634.java:465)
	at net.minecraft.class_2678.method_11567(class_2678.java:95)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['zsexdrctfvyg'/1136613, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/RT Carpet Addon 1.0.2.zip, file/Redstone Tweaks 2.3.zip, fabric

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 501616144 bytes (478 MiB) / 1140850688 bytes (1088 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12400F
	Identifier: Intel64 Family 6 Model 151 Stepping 5
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 73365.60
	Virtual memory used (MB): 61656.36
	Swap memory total (MB): 40784.18
	Swap memory used (MB): 1800.96
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bbor: BoundingBoxOutlineReloaded 2.6-1.20-rc1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
		carpet: Carpet Mod 1.4.112+v230608
		clientcommands: Client Commands 2.8.1
			betterconfig: BetterConfig 1.1.1
			clientarguments: clientarguments 1.5
		fabric-api: Fabric API 0.83.0+1.20
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c927
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b27
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d127
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b27
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b27
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f27
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b27
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b327
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b327
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b27
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b27
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe27
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.10+b3afc78b27
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b27
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b27
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b27
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b327
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a27
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b27
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b27
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b327
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b27
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c627
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b27
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b27
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b27
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b27
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b327
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b27
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b27
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b27
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b27
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b327
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b327
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b27
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.4+b3afc78b27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b27
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b27
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b27
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b27
		fabricloader: Fabric Loader 0.14.21
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.15.0
		logical_zoom: Logical Zoom 0.0.20
		malilib: MaLiLib 0.16.0
		minecraft: Minecraft 1.20
		seedcrackerx: SeedCrackerX 2.14.4
			cloth-config: Cloth Config v11 11.0.98
				cloth-basic-math: cloth-basic-math 0.6.1
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome 41a42cb9019a552598f12089059538853e18ec78
			com_seedfinding_mc_core: mc_core d64d5f90be66300da41ef58f4f1736db2499784f
			com_seedfinding_mc_feature: mc_feature 919b7e513cc1e87e029a9cd703fc4e2dc8686229
			com_seedfinding_mc_math: mc_math ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91
			com_seedfinding_mc_noise: mc_noise 7e3ba65e181796c4a2a1c8881d840b2254b92962
			com_seedfinding_mc_reversal: mc_reversal ca64c0890c106f1a2207623c316fce86f250b918
			com_seedfinding_mc_seed: mc_seed 1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409
			com_seedfinding_mc_terrain: mc_terrain b4246cbd5880c4f8745ccb90e1b102bde3448126
		sodium: Sodium 0.4.10+build.27
		tweakeroo: Tweakeroo 0.17.0
		viafabricplus: ViaFabricPlus 2.7.6
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.7
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaeroworldmap: Xaero's World Map 1.30.6
	Loaded Shaderpack: ComplementaryReimagined_r2.2.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/RT Carpet Addon 1.0.2.zip, file/Redstone Tweaks 2.3.zip, fabric
	Current Language: en_US
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12400F
```

**Comment by Earthcomputer** [comment]
This is an issue with seedcrackerx, not clientcommands.

**Comment by FatSake** [comment]
oh sorry, ive played with seed cracker and it works fine alone so i didnt think about it at all, thanks <3
