### ISSUE TITLE
Crashing whenever entering singleplayer world

### ISSUE THREAD

**Issue by Catsef** [Earthcomputer/clientcommands#584]
Version: 1.20.1 fabric 0.15.3 using PolyMC

```
[21:27:05] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[21:27:05] [Server thread/INFO]: Generating keypair
[21:27:05] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:27:07] [Render thread/INFO]: Preparing spawn area: 0%
[21:27:07] [Render thread/INFO]: Preparing spawn area: 0%
[21:27:07] [Render thread/INFO]: Preparing spawn area: 0%
[21:27:07] [Render thread/INFO]: Preparing spawn area: 0%
[21:27:07] [Render thread/INFO]: Preparing spawn area: 0%
[21:27:08] [Render thread/INFO]: Preparing spawn area: 0%
[21:27:08] [Render thread/INFO]: Preparing spawn area: 0%
[21:27:09] [Render thread/INFO]: Preparing spawn area: 4%
[21:27:09] [Render thread/INFO]: Preparing spawn area: 58%
[21:27:09] [Render thread/INFO]: Time elapsed: 4222 ms
[21:27:10] [Server thread/INFO]: Changing view distance to 30, from 10
[21:27:10] [Server thread/INFO]: Changing simulation distance to 25, from 0
[21:27:10] [Netty Local Client IO #0/INFO]: Singleplayer Recording is disabled
[21:27:11] [Server thread/INFO]: tmnu[local:E:a63f21a4] logged in with entity id 93 at (99.88495760024949, 63.0, 750.5021827104523)
[21:27:11] [Render thread/INFO]: New minimap session initialized!
[21:27:12] [Render thread/WARN]: Method overwrite conflict for getChunks in meteor-client.mixins.json:ClientChunkManagerAccessor from mod meteor-client, previously written by me.cominixo.betterf3.mixin.chunk.ClientChunkManagerMixin. Skipping method.
[21:27:12] [Render thread/WARN]: Method overwrite conflict for getChunks in betterf3.mixins.json:chunk.ClientChunkMapMixin from mod betterf3, previously written by baritone.launch.mixins.MixinChunkArray. Skipping method.
[21:27:12] [Render thread/WARN]: Method overwrite conflict for getChunks in meteor-client.mixins.json:ClientChunkMapAccessor from mod meteor-client, previously written by baritone.launch.mixins.MixinChunkArray. Skipping method.
[21:27:12] [Server thread/INFO]: tmnu joined the game
[21:27:20] [Render thread/INFO]: Started 10 worker threads
[21:27:20] [Render thread/INFO]: [STDOUT]: Baritone world data dir: C:\Users\blingo\AppData\Roaming\PolyMC\instances\1.20.1 - MGRT\.minecraft\saves\New World\.\baritone\minecraft\overworld_384
[21:27:20] [Render thread/INFO]: [STDOUT]: Cached world directory: C:\Users\blingo\AppData\Roaming\PolyMC\instances\1.20.1 - MGRT\.minecraft\saves\New World\.\baritone\minecraft\overworld_384\cache
[21:27:20] [Render thread/INFO]: [STDOUT]: Would save waypoints to C:\Users\blingo\AppData\Roaming\PolyMC\instances\1.20.1 - MGRT\.minecraft\saves\New World\.\baritone\minecraft\overworld_384\waypoints
[21:27:20] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 9998ms or 199 ticks behind
[21:27:21] [Render thread/INFO]: [Inventory Profiles Next] Loaded 1 external GUI hints
[21:27:21] [Render thread/INFO]: [Inventory Profiles Next] Loaded 783 build-in GUI hints
[21:27:21] [Render thread/INFO]: [Inventory Profiles Next] Effective GUI hints after merge: 784
[21:27:21] [Render thread/WARN]: Ambiguity between arguments [cfind, --keep-searching] and [cfind, filter] with inputs: [--keep-searching]
[21:27:21] [Render thread/INFO]: Using 3 total BufferBuilder caches
[21:27:21] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:21] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:21] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:21] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:21] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:21] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:21] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:21] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[21:27:23] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ExceptionInInitializerError: null
	at net.minecraft.class_634.handler$bmn002$seedcrackerx$onGameJoin(class_634.java:9751) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:465) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:25) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:213) ~[?:?]
	at java.util.List.of(List.java:979) ~[?:?]
	at kaptainwutax.seedcrackerX.config.StructureSave.<clinit>(StructureSave.java:29) ~[seedcrackerX-2.14.4.jar:?]
	... 22 more
[21:27:24] [Server thread/INFO]: Stopping server
[21:27:24] [Server thread/INFO]: Saving players
[21:27:24] [Server thread/INFO]: Saving worlds
[21:27:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Blue Day]'/minecraft:overworld
[21:27:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Blue Day]'/minecraft:the_nether
[21:27:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Blue Day]'/minecraft:the_end
[21:27:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[21:27:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:27:26] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:27:26] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[21:27:27] [Render thread/INFO]: Saving
[21:27:27] [Render thread/INFO]: Saved in 85 milliseconds.
[21:27:27] [Render thread/INFO]: Minimap session finalized.
[21:27:27] [Render thread/INFO]: Stopping JEI
[21:27:27] [Render thread/INFO]: Stopping JEI
[21:27:27] [Render thread/INFO]: Sending Runtime Unavailable...
[21:27:27] [Render thread/INFO]: Stopping JEI GUI
[21:27:27] [Render thread/INFO]: Sending Runtime Unavailable took 741.0 Î¼s
[21:27:27] [Render thread/INFO]: Stopping worker threads
---- Minecraft Crash Report ----
// There are four lights!
Time: 2024-01-03 21:27:27
Description: Unexpected error
java.lang.ExceptionInInitializerError
	at net.minecraft.class_634.handler$bmn002$seedcrackerx$onGameJoin(class_634.java:9751)
	at net.minecraft.class_634.method_11120(class_634.java:465)
	at net.minecraft.class_2678.method_11567(class_2678.java:95)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:213)
	at java.base/java.util.List.of(List.java:979)
	at kaptainwutax.seedcrackerX.config.StructureSave.<clinit>(StructureSave.java:29)
	... 22 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_634.handler$bmn002$seedcrackerx$onGameJoin(class_634.java:9751)
	at net.minecraft.class_634.method_11120(class_634.java:465)
	at net.minecraft.class_2678.method_11567(class_2678.java:95)
	at net.minecraft.class_2678.method_11054(class_2678.java:25)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
-- Affected level --
Details:
	All players: 1 total; [class_746['tmnu'/93, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 16384, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/! §bFaith War §8[§732§8].zip, replaymod_lang
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 19.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1153708160 bytes (1100 MiB) / 2803892224 bytes (2674 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: NVIDIA GeForce RTX 3060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2504
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 33516.29
	Virtual memory used (MB): 23616.54
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 1088.62
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		appleskin: AppleSkin 2.5.1+mc1.20
		betterf3: BetterF3 7.0.2
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cherishedworlds: Cherished Worlds 6.1.3+1.20.1
		cleardespawn: Clear Despawn 1.1.14
		clientcommands: Client Commands 2.8.4
			betterconfig: BetterConfig 1.2.1
			clientarguments: clientarguments 1.5
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		emojitype: Emoji Type 2.2.2+1.20.2
		experienceprogress: Experience Progress 1.1.0
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		ferritecore: FerriteCore 6.0.1
		freecam: Freecam (Modrinth Edition) 1.2.1+1.20
		gammautils: Gamma Utils 1.7.16
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		java: Java HotSpot(TM) 64-Bit Server VM 19
		jei: Just Enough Items 15.2.0.27
		jeresources: Just Enough Resources 1.4.0.238
		libipn: libIPN 4.0.0
		librarian-trade-finder: Librarian Trade Finder 2.0.1
		litematica: Litematica 0.15.3
		malilib: MaLiLib 0.16.3
		meteor-client: Meteor Client 0.5.4
			baritone-meteor: Baritone 1.20.1-SNAPSHOT
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.20
		replaymod: Replay Mod 1.20.1-2.6.13
		seedcrackerx: SeedCrackerX 2.14.4
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome 41a42cb9019a552598f12089059538853e18ec78
			com_seedfinding_mc_core: mc_core d64d5f90be66300da41ef58f4f1736db2499784f
			com_seedfinding_mc_feature: mc_feature 919b7e513cc1e87e029a9cd703fc4e2dc8686229
			com_seedfinding_mc_math: mc_math ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91
			com_seedfinding_mc_noise: mc_noise 7e3ba65e181796c4a2a1c8881d840b2254b92962
			com_seedfinding_mc_reversal: mc_reversal ca64c0890c106f1a2207623c316fce86f250b918
			com_seedfinding_mc_seed: mc_seed 1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409
			com_seedfinding_mc_terrain: mc_terrain b4246cbd5880c4f8745ccb90e1b102bde3448126
		sodium: Sodium 0.5.3
		villagertimetable: VillagerTimetable 1.0.0
		xaerominimap: Xaero's Minimap 23.9.3
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/! §bFaith War §8[§732§8].zip (incompatible)
	Current Language: en_us
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700
	Server Running: true
	Player Count: 1 / 8; [class_3222['tmnu'/93, l='ServerLevel[Blue Day]', x=99.88, y=63.00, z=750.50]]
	Data Packs: vanilla, fabric, file/treecapitator-v2-9.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
-- Meteor Client --
Version: 0.5.4
[[ Active Modules ]]
[Combat]:
kill-aura
[Movement]:
air-jump
boat-fly
fast-climb
[Render]:
esp
[World]:
nuker
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\blingo\AppData\Roaming\PolyMC\instances\1.20.1 - MGRT\.minecraft\crash-reports\crash-2024-01-03_21.27.27-client.txt
[21:27:27] [Thread-6/INFO]: Saving
[21:27:27] [Thread-6/INFO]: Saved in 32 milliseconds.
Process exited with code -1.
```

**Comment by Earthcomputer** [comment]
This is an issue with SeedCrackerX.

Also, you should avoid using PolyMC due to a hostile takeover that happened. Use its fork, [PrismLauncher](https://prismlauncher.org/), instead, which is better anyway.

**Comment by Catsef** [comment]
Thank you for the tip, will transfer!
