### ISSUE TITLE
`crelog` combined with Command Macros mod crashes the game

### ISSUE THREAD

**Issue by Mudxiej** [Earthcomputer/clientcommands#620]
I have binded "Pg Dw" in Command Macros mod as `crelog` which is a button on my mouse, it crashes my game. It quits the game after quiting the server.
I actually dont know if there are logs, so you have to guide me on what to sent 😅

**Comment by Earthcomputer** [comment]
Hi, the crash reports are in `.minecraft/crash-reports` and the logs are in `.minecraft/logs`

**Comment by Mudxiej** [comment]
Nevermind. 2 weeks ago it wasn't working, today it didnt work too, but now as i wanted to replicate the issue for the logs it works... Sorry for the trouble, but maybe you want to have my logs from where this problem occurred, and you could help telling me what was the error? 😅

**Comment by Mudxiej** [comment]
[2024-04-20-2.log.gz](https://github.com/Earthcomputer/clientcommands/files/15048390/2024-04-20-2.log.gz)
[2024-04-20-3.log.gz](https://github.com/Earthcomputer/clientcommands/files/15048391/2024-04-20-3.log.gz)
[crash-2024-04-20_12.31.08-client.txt](https://github.com/Earthcomputer/clientcommands/files/15048393/crash-2024-04-20_12.31.08-client.txt)
[crash-2024-04-20_12.36.16-client.txt](https://github.com/Earthcomputer/clientcommands/files/15048394/crash-2024-04-20_12.36.16-client.txt)
Should be in these, however im not sure now...

**Comment by Mudxiej** [comment]
```

**Comment by Mudxiej** [comment]
```
[16:39:11] [Render thread/INFO]: Connecting to [SERVER IP]
[16:39:11] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Exception while adding particle
	at net.minecraft.class_1937.method_18472(class_1937.java:499) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_32124(class_638.java:260) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:256) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2011) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot read field "field_9229" because "$$1" is null
	at net.minecraft.class_5786$class_5957.method_34749(class_5786.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_5786$class_5957.method_3090(class_5786.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_3055(class_702.java:354) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_3056(class_702.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3288(class_761.java:2524) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8563(class_761.java:2496) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_8568(class_761.java:2491) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_8406(class_638.java:609) ~[client-intermediary.jar:?]
	at net.minecraft.class_5776.method_6007(class_5776.java:78) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.basicTick(class_638.java:3663) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.handler$bih000$entityculling$tickEntity(class_638.java:3648) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:492) ~[client-intermediary.jar:?]
	... 18 more
[16:39:11] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[16:39:11] [Render thread/INFO]: Clearing 'BetterStatsClientNetworkHandler' flags.
[16:39:11] [CraftPresence/INFO]: Shutting down CraftPresence...
```
[crash-2024-04-20_16.39.11-client.txt](https://github.com/Earthcomputer/clientcommands/files/15048605/crash-2024-04-20_16.39.11-client.txt)

Happened again... Seems like there is some particle issue

**Comment by Mudxiej** [comment]
I think i know how to replicate the problem. Setting 2 commands (for my example `cghostfill` and `crelog`) makes minecraft crash

**Comment by xpple** [comment]
Closing as Command Macros is not available for recent Minecraft versions.
