### ISSUE TITLE
Game crash on autocomplete when using entity selector `@e[type=` 1.21.3

### ISSUE THREAD

**Issue by m-sarabi** [Earthcomputer/clientcommands#668]
## Description

The game crashes while trying to run `/cgetdata entity @e[type=pillager...` command (or any other commands to select entities like `/cglow` or `/cfind`) as soon as it wants to autocomplete (on the word `pillager` in the example).

## Steps to reproduce

- Type `/cgetdata @e[type=p`
- The game crashes as soon as it wants to autocomplete the word.

## Crash report:

[crash-2024-10-28_04.19.58-client.txt](https://github.com/user-attachments/files/17536124/crash-2024-10-28_04.19.58-client.txt)

<details>
<summary>Crash report</summary>

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-10-28 04:19:58
Description: charTyped event handler

java.lang.NoSuchMethodError: 'java.util.stream.Stream net.minecraft.class_7922.method_40273()'
	at knot//dev.xpple.clientarguments.arguments.CEntitySelectorOptions.lambda$register$40(CEntitySelectorOptions.java:210)
	at knot//dev.xpple.clientarguments.arguments.CEntitySelectorReader.listSuggestions(CEntitySelectorReader.java:486)
	at knot//dev.xpple.clientarguments.arguments.CEntityArgument.listSuggestions(CEntityArgument.java:118)
	at knot//com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:69)
	at knot//com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:541)
	at knot//net.minecraft.class_4717.method_23934(class_4717.java:214)
	at knot//net.minecraft.class_408.method_23945(class_408.java:85)
	at knot//net.minecraft.class_342.method_1874(class_342.java:155)
	at knot//net.minecraft.class_342.method_1867(class_342.java:150)
	at knot//net.minecraft.class_342.method_25400(class_342.java:358)
	at knot//net.minecraft.class_4069.method_25400(class_4069.java:90)
	at knot//net.minecraft.class_309.method_1457(class_309.java:508)
	at knot//net.minecraft.class_309.method_22677(class_309.java:528)
	at knot//net.minecraft.class_1255.execute(class_1255.java:110)
	at knot//net.minecraft.class_309.method_22675(class_309.java:528)
	at knot//org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:149)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:170)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:314)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1370)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//dev.xpple.clientarguments.arguments.CEntitySelectorOptions.lambda$register$40(CEntitySelectorOptions.java:210)
	at knot//dev.xpple.clientarguments.arguments.CEntitySelectorReader.listSuggestions(CEntitySelectorReader.java:486)
	at knot//dev.xpple.clientarguments.arguments.CEntityArgument.listSuggestions(CEntityArgument.java:118)
	at knot//com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:69)
	at knot//com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:541)
	at knot//net.minecraft.class_4717.method_23934(class_4717.java:214)
	at knot//net.minecraft.class_408.method_23945(class_408.java:85)
	at knot//net.minecraft.class_342.method_1874(class_342.java:155)
	at knot//net.minecraft.class_342.method_1867(class_342.java:150)
	at knot//net.minecraft.class_342.method_25400(class_342.java:358)
	at knot//net.minecraft.class_4069.method_25400(class_4069.java:90)
	at knot//net.minecraft.class_309.method_1457(class_309.java:508)
	at knot//net.minecraft.class_309.method_22677(class_309.java:528)
	at knot//net.minecraft.class_1255.execute(class_1255.java:110)
	at knot//net.minecraft.class_309.method_22675(class_309.java:528)
	at knot//org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:149)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:170)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at knot//net.minecraft.class_309.method_1457(class_309.java:508)
	at knot//net.minecraft.class_309.method_22677(class_309.java:528)
	at knot//net.minecraft.class_1255.execute(class_1255.java:110)
	at knot//net.minecraft.class_309.method_22675(class_309.java:528)
	at knot//org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:149)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:170)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:314)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1370)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Key --
Details:
	Codepoint: 105
	Mods: 0
Stacktrace:
	at knot//net.minecraft.class_309.method_1457(class_309.java:508)
	at knot//net.minecraft.class_309.method_22677(class_309.java:528)
	at knot//net.minecraft.class_1255.execute(class_1255.java:110)
	at knot//net.minecraft.class_309.method_22675(class_309.java:528)
	at knot//org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:149)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:170)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:314)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1370)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 1240.773s
	Wall uptime: 1203.266s
	High-res time: 1196.898s
	Client ticks: 23477 ticks / 1173.850s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Funzen'/1401392, l='ClientLevel', x=115853.18, y=67.00, z=147717.35]]
	Chunk stats: 2025, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-512,64,160), Section: (at 0,0,0 in -32,4,10; chunk contains blocks -512,-64,160 to -497,319,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 1480205868 game time, 3581682366 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
	Tracked entity count: 82

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, advancements_reloaded, badoptimizations, betterconfig, carpet, clientcommands, cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fadeless, immediatelyfast, itemscroller, journeymap, litematica, malilib, midnightlib, minihud, modmenu, reeses-sodium-options, sodium, sodium-extra, tweakeroo, file/FunzenPack

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 933189952 bytes (889 MiB) / 1476395008 bytes (1408 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2.39
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 20.19.15.4624
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MiB): 17321.85
	Virtual memory used (MiB): 9535.00
	Swap memory total (MiB): 1024.00
	Swap memory used (MiB): 62.84
	Space in storage for jna.tmpdir (MiB): available: 23817.43, total: 243347.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 23817.43, total: 243347.00
	Space in storage for io.netty.native.workdir (MiB): available: 23817.43, total: 243347.00
	Space in storage for java.io.tmpdir (MiB): available: 23817.43, total: 243347.00
	Space in storage for workdir (MiB): available: 23817.43, total: 243347.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancements_reloaded: Advancements Reloaded 0.6.1
			cloth-config: Cloth Config v15 15.0.127
				cloth-basic-math: cloth-basic-math 0.6.1
		badoptimizations: BadOptimizations 2.2.0
		carpet: Carpet Mod 1.4.158+v241022
		clientcommands: Client Commands 2.9.5
			betterconfig: BetterConfig 2.1.2
			clientarguments: clientarguments 1.9
			net_fabricmc_mapping-io: mapping-io 0.5.1
		fabric-api: Fabric API 0.106.1+1.21.3
			fabric-api-base: Fabric API Base 0.4.48+2127dc7240
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.78+c47b9d4340
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.5+c47b9d4340
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+c47b9d4340
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+c47b9d4340
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.2+c47b9d4340
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.22+c47b9d4340
			fabric-command-api-v1: Fabric Command API (v1) 1.2.56+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.35+c47b9d4340
			fabric-commands-v0: Fabric Commands (v0) 0.2.73+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.5+c47b9d4340
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.0+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.0+c47b9d4340
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+c47b9d4340
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.38+c47b9d4340
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.14+c47b9d4340
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+c47b9d4340
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.5+c47b9d4340
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.9+c47b9d4340
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+c47b9d4340
			fabric-item-api-v1: Fabric Item API (v1) 11.1.5+c47b9d4340
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.15+e7c9ab6640
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+c47b9d4340
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.22+c47b9d4340
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.24+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.12+c47b9d4340
			fabric-message-api-v1: Fabric Message API (v1) 6.0.19+c47b9d4340
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.7+c47b9d4340
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.3+56ec7ac640
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.7+c47b9d4340
			fabric-particles-v1: Fabric Particles (v1) 4.0.8+c47b9d4340
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.2+c47b9d4340
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+56ec7ac640
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.3+c47b9d4340
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.3+c47b9d4340
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.13+c47b9d4340
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.81+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.5+c47b9d4340
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+c47b9d4340
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.5+c47b9d4340
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.32+c47b9d4340
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.98+c47b9d4340
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+c47b9d4340
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.0+c47b9d4340
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+c47b9d4340
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		fadeless: Fadeless 2.0.1
			midnightlib: MidnightLib 1.6.3
		ferritecore: FerriteCore 7.1.0-hotfix
		immediatelyfast: ImmediatelyFast 1.3.0+1.21.3
			net_lenni0451_reflect: Reflect 1.3.4
		itemscroller: Item Scroller 0.25.0-sakura.2
		java: OpenJDK 64-Bit Server VM 21
		journeymap: Journeymap 1.21.3-6.0.0-beta.28
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.17-1.21.3
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21.3-SNAPSHOT
		litematica: Litematica 0.20.0-sakura.2
		malilib: MaLiLib 0.22.0-sakura.2
		minecraft: Minecraft 1.21.3
		minihud: MiniHUD 0.33.0-sakura.2
		modmenu: Mod Menu 12.0.0-beta.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.5+mc1.21.3
		sodium: Sodium 0.6.0-beta.3+mc1.21.2
		sodium-extra: Sodium Extra 0.6.0-beta.4+mc1.21.3
		tweakeroo: Tweakeroo 0.22.0-sakura.2
	Launched Version: fabric-loader-0.16.7-1.21.3
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Intel(R) HD Graphics 5500 GL version 3.2.0 - Build 20.19.15.4624, Intel
	Window size: 1600x900
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, advancements_reloaded, badoptimizations (incompatible), betterconfig, carpet, clientcommands (incompatible), cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fadeless, immediatelyfast, itemscroller, journeymap, litematica, malilib, midnightlib, minihud, modmenu, reeses-sodium-options, sodium, sodium-extra, tweakeroo (incompatible), file/FunzenPack (incompatible)
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
```

</details>

<details>
<summary>mods:</summary>

```
advancements_reloaded-0.6.1-fabric-1.21.1.jar
BadOptimizations-2.2.0-1.21.2.jar
clientcommands-2.9.5.jar
fabric-api-0.106.1+1.21.3.jar
fabric-carpet-1.21.2-1.4.158+v241022.jar
fadeless-2.0.1.jar
ferritecore-7.1.0-hotfix-fabric.jar
ImmediatelyFast-Fabric-1.3.0+1.21.3.jar
itemscroller-fabric-1.21.3-0.25.0-sakura.2.jar
journeymap-fabric-1.21.3-6.0.0-beta.28.jar
litematica-fabric-1.21.3-0.20.0-sakura.2.jar
malilib-fabric-1.21.3-0.22.0-sakura.2.jar
minihud-fabric-1.21.3-0.33.0-sakura.2.jar
modmenu-12.0.0-beta.1.jar
reeses-sodium-options-fabric-1.8.0-beta.5+mc1.21.3.jar
sodium-extra-fabric-0.6.0-beta.4+mc1.21.3.jar
sodium-fabric-0.6.0-beta.3+mc1.21.2.jar
tweakeroo-fabric-1.21.3-0.22.0-sakura.2.jar
```

</details>

**Comment by Earthcomputer** [comment]
https://github.com/Earthcomputer/clientcommands/pull/669
